#!/bin/bash

# Find the real system npx
REAL_NPX=$(which -a npx | grep -v "/usr/local/bin/npx" | head -n 1)

# If the package exists locally in node_modules/.bin, it's safe to run
if [ -f "./node_modules/.bin/$1" ]; then
    exec "$REAL_NPX" "$@"
else
    echo -e "\e[31m[BLOCKED]\e[0m Raw 'npx' is disabled for remote packages."

    # Prompt the user to run with snx instead if the environment is interactive
    if [ -t 1 ]; then
        read -p "Would you like to run 'snx $*' instead? (Y/n): " choice < /dev/tty
        if [[ -z "$choice" || "$choice" =~ ^[Yy]$ ]]; then
            exec /usr/local/bin/snx "$@"
        else
            echo -e "\e[31mCommand aborted.\e[0m"
            exit 1
        fi
    else
        exit 1
    fi
fi
